In [1]:
import numpy as np
P=np.array([[1,7],[2,1],[3,4]])
Q=np.array([[1,7],[2,1],[3,4]])

In [2]:
np.add(P,Q)

array([[ 2, 14],
       [ 4,  2],
       [ 6,  8]])

In [3]:
np.subtract(P,Q)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [4]:
r=np.array([[1,7,5],[2,1,6]])

In [6]:
 c= np.dot(P,r)

In [7]:
print(c)

[[15 14 47]
 [ 4 15 16]
 [11 25 39]]


In [8]:
np.linalg.det(c)

4.630074101896776e-13

In [9]:
np.linalg.inv(c)

array([[ 3.99561640e+14,  1.35850957e+15, -1.03886026e+15],
       [ 4.31958529e+13,  1.46865900e+14, -1.12309218e+14],
       [-1.40386522e+14, -4.77314175e+14,  3.65004957e+14]])