In [1]:
import numpy as np


# Initializing Vectors

In [ ]:
v=np.array([1,-1,2])
w=np.array([2,5,2])


# Vector ADDITION

In [8]:
v+w

array([3, 4, 4])

# Vector Subtraction

In [4]:
v-w

array([-1, -6,  0])

# Scaler Multiplication

In [5]:
v*3

array([ 3, -3,  6])

# Finding Length of Vectors

In [6]:
np.linalg.norm(v)

2.449489742783178

# Dot Product of two vectors

In [7]:
np.dot(v,w)

1